apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron
  namespace: firefly-iii-ns
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron
              image: alpine
              command: ["sh", "-c", "wget -qO- http://app:8080/api/v1/cron/REPLACEME"]
          restartPolicy: OnFailure
          hostNetwork: true
