apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-data
  namespace: firefly-iii-ns
  labels:
    app: firefly-iii
apiVersion: v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi