apiVersion: v1
kind: Secret
metadata:
  name: firefly-iii-env
type: Opaque
data:
  # Application configuration
  APP_URL: https://firefly.310networks.com
  APP_ENV: local
  APP_DEBUG: false
  SITE_OWNER: daniel@310networks.com
  APP_KEY: SomeRandomStringOf32CharsExactly
  AUTHENTICATION_GUARD: web
  DEFAULT_LANGUAGE: en_US
  DEFAULT_LOCALE: equal
  TZ: Pacific/Honolulu
  TRUSTED_PROXIES: **
  LOG_CHANNEL: STACK
  APP_LOG_LEVEL: notice
  AUDIT_LOG_LEVEL: info
  MAP_DEFAULT_LAT: 19.618650
  MAP_DEFAULT_LONG: -155.037155
  MAP_DEFAULT_ZOOM: 6
  # Database configuration
  DB_CONNECTION: mysql
  DB_HOST: db
  DB_PORT: 3306
  DB_DATABASE: firefly
  DB_USERNAME: firefly
  DB_PASSWORD: secret_firefly_password
  # Email server configuration
  MAIL_MAILER: smtp
  MAIL_HOST: smtp.sendgrid.net
  MAIL_PORT: 587
  MAIL_FROM: fireflyiii@310networks.com
  MAIL_USERNAME: apikey
  MAIL_PASSWORD: 
  MAIL_ENCRYPTION: tls
  # Email settings configuration
  SEND_ERROR_MESSAGE: true
  SEND_REPORT_JOURNALS: true
  # Cron Token
  STATIC_CRON_TOKEN: 
---
apiVersion: v1
kind: Secret
metadata:
  name: db-env
type: Opaque
data:
  MYSQL_RANDOM_ROOT_PASSWORD: yes
  MYSQL_USER: firefly
  MYSQL_PASSWORD: secret_firefly_password
  MYSQL_DATABASE: firefly
---
apiVersion: v1
kind: Secret
metadata:
  name: importer-env
type: Opaque
data:
  # Application configuration
  APP_NAME: DataImporter
  FIREFLY_III_URL: http://app:8080
  VANITY_URL: https://firefly.310networks.com
  APP_ENV: local
  APP_DEBUG: false
  LOG_CHANNEL: stack
  LOG_LEVEL: debug
  TRUSTED_PROXIES: **
  TZ: Pacific/Honolulu
  # Email server configuration
  MAIL_DESTINATION: daniel@310networks.com
  MAIL_MAILER: smtp
  MAIL_HOST: smtp.sendgrid.net
  MAIL_PORT: 587
  MAIL_FROM: fireflyiii@310networks.com
  MAIL_USERNAME: apikey
  MAIL_PASSWORD: 
  MAIL_ENCRYPTION: tls
