apiVersion: apps/v1
kind: Service
metadata:
  name: fireflyiii
  namespace: fireflyiii
  labels:
    app: fireflyiii
apiVersion: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  selector:
    app: fireflyiii